# File generated by CompCert 3.14
# Command line: -O2 -S -o __compcert_i64_dtos.s -I./c c/__compcert_i64_dtos.c
	.option nopic
	.text
	.balign 2
	.globl __compcert_i64_dtos
__compcert_i64_dtos:
	mv	x30, x2
	addi	x2, x2, -32
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	sw	x8, 8(x2)
	fsd	f10, 16(x2)
	lw	x10, 16(x2)
	lw	x8, 20(x2)
	lui	x31, 524032
	and	x12, x8, x31
	srli	x13, x12, 20
	addi	x12, x13, -1075
	addi	x31, x0, -52
	bge	x12, x31, .L100
	addi	x11, x0, 0
	addi	x10, x0, 0
	j	.L101
.L100:
	addi	x31, x0, 11
	blt	x12, x31, .L102
	blt	x8, x0, .L103
	lui	x11, 524288
	addi	x11, x11, -1
	addi	x10, x0, -1
	j	.L101
.L103:
	lui	x11, 524288
	addi	x10, x0, 0
	j	.L101
.L102:
	lui	x31, 256
	addi	x31, x31, -1
	and	x5, x8, x31
	lui	x31, 256
	or	x11, x5, x31
	bge	x12, x0, .L104
	sub	x12, x0, x12
	call	__compcert_i64_shr
	j	.L105
.L104:
	call	__compcert_i64_shl
.L105:
	bge	x8, x0, .L101
	sltu	x1, x0, x10
	sub	x10, x0, x10
	sub	x11, x0, x11
	sub	x11, x11, x1
.L101:
	lw	x8, 8(x2)
	lw	x1, 4(x2)
	addi	x2, x2, 32
	jr	x1
	.type	__compcert_i64_dtos, @function
	.size	__compcert_i64_dtos, . - __compcert_i64_dtos
